deploymentName: eurekaserver-deployment
serviceName: eurekaserver
appLabel: eurekaserver
appName: eurekaserver

replicaCount: 1

image:
  repository: prabal864/java-spring
  tag: Eureka-Server-S15

containerPort: 8761

service:
  type: ClusterIP
  port: 8761
  targetPort: 8761

appname_enabled: true
profile_enabled: false
config_enabled: true
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false