spring:
  application:
    name: "cloud_config"

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: "file:///D://Coding//Java Course//Spring-Project//SpringBootMicroservice-Config//V2_Cloud_Config//cloud_config//src//main//resources//config"


server:
  port: 8084

