build:
  version: "0.0.3"

cards:
  message: "Welcome to PRODUCTION-1 environment Cards Microservice"
  contactDetails:
    name: "Production Team"
    email: "production@test.com"

  onCallSupport:
    - "999-456-7890"
    - "999-765-4321"

