apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      name: gateway
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: prabal864/java-spring:Gateway-Server-S15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8072
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://configserver:8084/"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-service:8761/eureka/"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
              value: "http://keycloak-service:8070/realms/master/protocol/openid-connect/certs"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis-service"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"


---

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8072
      targetPort: 8072
