server:
  port: 8083
spring:
  application:
    name: "cards"

  config:
    import: "optional:configserver:http://configserver:8084/"

  profiles:
    active: qa

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://cardsdb:3308/cards_db}
    username: ${SPRING_DATASOURCE_URL:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always

  rabbitmq:
    host: "rabbit"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/

info:
  app:
    name: "cards"
    description: "Cards Microservice"
    version: "1.0.0"