server:
  port: 9091

spring:
  application:
    name: "message"

  cloud:
    function:
      definition: email|sms

    stream:
      bindings:
        emailsms-in-0:
          destination: send-communication
          group: message
        emailsms-out-0:
            destination: communication-sent
            
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s
