{{- define "common.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.global.configMapName}}
data:
  SPRING_PROFILES_ACTIVE: "{{ .Values.global.activeProfile}}"
  SPRING_CONFIG_IMPORT: "{{ .Values.global.configServerURL }}"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "{{ .Values.global.eurekaServerURL }}"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "{{ .Values.global.keyCloakURL }}"
  JAVA_TOOL_OPTIONS: "{{ .Values.global.openTelemetryJavaAgent }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.global.otelExporterEndPoint }}"
  OTEL_METRICS_EXPORTER: "{{ .Values.global.otelMetricsExporter }}"
  OTEL_LOGS_EXPORTER: "{{ .Values.global.otelLogsExporter }}"
  SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: "{{ .Values.global.kafkaBrokerURL }}"
  RABBITMQ_USERNAME: "{{ .Values.global.rabbitmqUsername }}"
  RABBITMQ_PASSWORD: "{{ .Values.global.rabbitmqPassword }}"
  RABBITMQ_HOST: "{{ .Values.global.rabbitmqHost | default "rabbitmq.default.svc.cluster.local" }}"
  RABBITMQ_PORT: "{{ .Values.global.rabbitmqPort | default "5672" }}"
  {{- end -}}