spring:
  application:
    name: "gatewayserver"
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8084/}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: ${SPRING_DATASOURCE_URL:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted

  info:
    env:
      enabled: true

logging:
  level:
    com:
      micronauticals:
        gateway_server: DEBUG

info:
  app:
    name: "gatewayserver"
    description: "gatewayserver Microservice"
    version: "1.0.0"

