server:
  port: 8081

spring:
    application:
      name: "accounts"

    config:
      import: "optional:configserver:http://configserver:8084/"

    profiles:
      active: "prod"

    datasource:
        url: jdbc:h2:mem:springbootdb
        username: sa
        password: ''
        driver-class-name: org.h2.Driver

    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            transaction:
              jta:
                platform: org.hibernate.service.jta.platform.internal.NoJtaPlatform

    h2:
        console:
          enabled: true

    rabbitmq:
      host: "rabbit"
      port: 5672
      username: "guest"
      password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
