server:
  port: 8081

spring:
    application:
      name: SpringBootMicroservice
    datasource:
        url: jdbc:h2:mem:springbootdb
        username: sa
        password: ''
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
    h2:
        console:
          enabled: true

build:
  version: "0.0.1"

accounts:
  message: "Welcome to Accounts Microservice"
  contactDetails:
    email: "pps@test.com"
    name: "PPS-940"

  onCallSupport:
    - "123-456-7890"
    - "098-765-4321"
