server:
  port: 8081

spring:
    application:
      name: "accounts"
    config:
      import: "optional:configserver:http://configserver:8084/"
    profiles:
      active: "prod"
    datasource:
      url: jdbc:mysql://localhost:3306/accounts_db
      username: root
      password: root
    jpa:
        show-sql: true
        hibernate:
          ddl-auto: update
    sql:
      init:
        mode: always
    rabbitmq:
      host: ${SPRING_RABBITMQ_HOST:localhost}
      port: 5672
      username: "guest"
      password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted


eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


info:
  app:
    name: "accounts"
    description: "Accounts Microservice"
    version: "1.0.0"

